import type { Resource, Values } from "../care/types";

const accountLookup = {
  type: "lookup" as const,
  source: "/finance/accounts",
  labelKeys: ["code", "name"],
};

export const financeResources: Resource[] = [
  {
    path: "/finance/accounts",
    title: "Chart of accounts",
    permission: "finance.view",
    writePermission: "finance.configure",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Account" },
      { key: "type", label: "Type" },
      { key: "normal_balance", label: "Balance" },
    ],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Account name", type: "text", required: true },
      {
        name: "type",
        label: "Account type",
        type: "select",
        options: ["ASSET", "LIABILITY", "EQUITY", "REVENUE", "EXPENSE", "COGS"],
        required: true,
      },
      {
        name: "normal_balance",
        label: "Normal balance",
        type: "select",
        options: ["DEBIT", "CREDIT"],
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox", default: true },
    ],
  },
  {
    path: "/finance/fiscal-periods",
    title: "Fiscal periods",
    permission: "finance.view",
    writePermission: "finance.configure",
    columns: [
      { key: "name", label: "Period" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Period name", type: "text", required: true },
      { name: "start_date", label: "Start date", type: "date", required: true },
      { name: "end_date", label: "End date", type: "date", required: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    statusOptions: ["OPEN", "LOCKED", "CLOSED"],
    actions: [
      {
        label: "Lock period",
        permission: "finance.configure",
        path: (record) => `/finance/fiscal-periods/${record.id}/lock`,
        fields: [],
        visible: (record) => record.status === "OPEN",
      },
      {
        label: "Close period",
        permission: "finance.configure",
        path: (record) => `/finance/fiscal-periods/${record.id}/close`,
        fields: [],
        visible: (record) => record.status !== "CLOSED",
      },
      {
        label: "Reopen period",
        permission: "finance.configure",
        path: (record) => `/finance/fiscal-periods/${record.id}/reopen`,
        fields: [],
        visible: (record) => record.status !== "OPEN",
      },
    ],
  },
  {
    path: "/finance/journals",
    title: "Journal entries",
    permission: "finance.view",
    writePermission: "finance.edit",
    columns: [
      { key: "entry_date", label: "Date" },
      { key: "reference", label: "Reference" },
      { key: "posting_type", label: "Posting" },
      { key: "total_debit", label: "Debit" },
      { key: "total_credit", label: "Credit" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "entry_date", label: "Date", type: "date", required: true },
      { name: "reference", label: "Reference", type: "text" },
      { name: "description", label: "Description", type: "textarea", required: true },
      {
        name: "lines",
        label: "Journal lines",
        type: "array",
        required: true,
        fields: [
          { name: "account_id", label: "Account", ...accountLookup, required: true },
          { name: "debit", label: "Debit", type: "number", default: 0 },
          { name: "credit", label: "Credit", type: "number", default: 0 },
          { name: "description", label: "Line memo", type: "text" },
        ],
      },
    ],
    statusOptions: ["DRAFT", "SUBMITTED", "POSTED", "REVERSED"],
    actions: [
      {
        label: "Approve journal",
        permission: "finance.approve",
        path: (record) => `/finance/journals/${record.id}/approve`,
        fields: [],
        visible: (record) => record.status === "DRAFT" || record.status === "SUBMITTED",
      },
      {
        label: "Reverse journal",
        permission: "finance.approve",
        path: (record) => `/finance/journals/${record.id}/reverse`,
        fields: [],
        visible: (record) => record.status === "POSTED",
      },
    ],
  },
  {
    path: "/finance/expense-categories",
    title: "Expense categories",
    permission: "finance.view",
    writePermission: "finance.configure",
    columns: [
      { key: "name", label: "Category" },
      { key: "account_id", label: "Account" },
      { key: "is_active", label: "Active" },
    ],
    fields: [
      { name: "name", label: "Category name", type: "text", required: true },
      { name: "account_id", label: "Expense account", ...accountLookup, required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox", default: true },
    ],
  },
  {
    path: "/finance/expenses",
    title: "Expense vouchers",
    permission: "finance.view",
    writePermission: "finance.edit",
    columns: [
      { key: "expense_date", label: "Date" },
      { key: "paid_to", label: "Paid to" },
      { key: "payment_method", label: "Method" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      {
        name: "expense_category_id",
        label: "Category",
        type: "lookup",
        source: "/finance/expense-categories",
        labelKeys: ["name"],
        required: true,
      },
      { name: "amount", label: "Amount", type: "number", required: true },
      {
        name: "payment_method",
        label: "Payment method",
        type: "select",
        options: ["CASH", "MPESA", "CARD", "BANK", "TRANSFER"],
        required: true,
      },
      { name: "payment_account_id", label: "Payment account", ...accountLookup },
      { name: "paid_to", label: "Paid to", type: "text", required: true },
      { name: "reference", label: "Reference", type: "text" },
      { name: "expense_date", label: "Expense date", type: "date", required: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
    statusOptions: ["DRAFT", "APPROVED"],
    actions: [
      {
        label: "Approve expense",
        permission: "finance.approve",
        path: (record) => `/finance/expenses/${record.id}/approve`,
        fields: [],
        visible: (record) => record.status === "DRAFT",
      },
    ],
  },
  {
    path: "/finance/suppliers",
    title: "Suppliers",
    permission: "finance.view",
    writePermission: "finance.edit",
    columns: [
      { key: "name", label: "Supplier" },
      { key: "contact_person", label: "Contact" },
      { key: "phone", label: "Phone" },
      { key: "tax_pin", label: "Tax PIN" },
    ],
    fields: [
      { name: "name", label: "Supplier name", type: "text", required: true },
      { name: "contact_person", label: "Contact person", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "tax_pin", label: "Tax PIN", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
    ],
  },
  {
    path: "/finance/supplier-invoices",
    title: "Supplier invoices",
    permission: "finance.view",
    writePermission: "finance.edit",
    columns: [
      { key: "invoice_date", label: "Date" },
      { key: "invoice_number", label: "Invoice" },
      { key: "invoice_type", label: "Type" },
      { key: "total_amount", label: "Total" },
      { key: "status", label: "Status" },
    ],
    fields: [
      {
        name: "supplier_id",
        label: "Supplier",
        type: "lookup",
        source: "/finance/suppliers",
        labelKeys: ["name"],
        required: true,
      },
      { name: "invoice_number", label: "Invoice number", type: "text", required: true },
      { name: "invoice_date", label: "Invoice date", type: "date", required: true },
      { name: "due_date", label: "Due date", type: "date", required: true },
      {
        name: "invoice_type",
        label: "Invoice type",
        type: "select",
        options: ["DIRECT_EXPENSE", "INVENTORY", "SERVICE"],
        default: "DIRECT_EXPENSE",
      },
      {
        name: "items",
        label: "Invoice lines",
        type: "array",
        required: true,
        fields: [
          { name: "account_id", label: "Posting account", ...accountLookup, required: true },
          { name: "description", label: "Description", type: "text", required: true },
          { name: "quantity", label: "Quantity", type: "number", default: 1 },
          { name: "unit_cost", label: "Unit cost", type: "number", required: true },
          { name: "discount", label: "Discount", type: "number", default: 0 },
          { name: "tax_rate", label: "VAT rate", type: "number", default: 0 },
        ],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    statusOptions: ["SUBMITTED", "APPROVED", "PARTIAL", "PAID"],
    actions: [
      {
        label: "Approve invoice",
        permission: "finance.approve",
        path: (record) => `/finance/supplier-invoices/${record.id}/approve`,
        fields: [],
        visible: (record) => record.status === "SUBMITTED",
      },
      {
        label: "Record payment",
        permission: "finance.edit",
        path: (record) => `/finance/supplier-invoices/${record.id}/pay`,
        fields: [
          { name: "amount", label: "Amount", type: "number", required: true },
          {
            name: "payment_method",
            label: "Payment method",
            type: "select",
            options: ["CASH", "MPESA", "CARD", "BANK", "TRANSFER"],
            required: true,
          },
          { name: "payment_account_id", label: "Payment account", ...accountLookup, required: true },
          { name: "payment_reference", label: "Reference", type: "text" },
          { name: "payment_date", label: "Payment date", type: "date", required: true },
        ],
        defaults: (record): Values => ({ amount: record.total_amount }),
        visible: (record) => record.status === "APPROVED" || record.status === "PARTIAL",
      },
    ],
  },
  {
    path: "/finance/cash-reconciliations",
    title: "Cash reconciliation",
    permission: "finance.view",
    writePermission: "finance.edit",
    columns: [
      { key: "period_date", label: "Date" },
      { key: "cashier_name", label: "Cashier" },
      { key: "expected_cash", label: "Expected" },
      { key: "counted_cash", label: "Counted" },
      { key: "variance", label: "Variance" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "period_date", label: "Date", type: "date", required: true },
      { name: "cashier_name", label: "Cashier", type: "text" },
      { name: "opening_cash", label: "Opening cash", type: "number", default: 0 },
      { name: "expected_cash", label: "Expected cash", type: "number", required: true },
      { name: "counted_cash", label: "Counted cash", type: "number", required: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    path: "/finance/payment-reconciliations",
    title: "M-Pesa and payment reconciliation",
    permission: "finance.view",
    writePermission: "finance.edit",
    columns: [
      { key: "period_date", label: "Date" },
      { key: "method", label: "Method" },
      { key: "system_total", label: "System" },
      { key: "statement_total", label: "Statement" },
      { key: "variance", label: "Variance" },
      { key: "status", label: "Status" },
    ],
    fields: [
      {
        name: "method",
        label: "Method",
        type: "select",
        options: ["MPESA", "CARD", "BANK", "INSURANCE"],
        required: true,
      },
      { name: "period_date", label: "Date", type: "date", required: true },
      { name: "system_total", label: "System total", type: "number", required: true },
      { name: "statement_total", label: "Statement total", type: "number", required: true },
      { name: "missing_references", label: "Missing references", type: "textarea" },
      { name: "duplicate_references", label: "Duplicate references", type: "textarea" },
    ],
  },
];
