import {
  attendance,
  check,
  choice,
  date,
  lookup,
  note,
  number,
  staff,
  stamp,
  strings,
  text,
} from "../care/fields";
import type { Field, Resource } from "../care/types";

const sessionTypes = [
  "INDIVIDUAL_COUNSELLING",
  "GROUP_COUNSELLING",
  "FAMILY_THERAPY",
  "PSYCHOEDUCATION",
  "ADDICTION_COUNSELLING",
  "CBT",
  "RELAPSE_PREVENTION",
  "TRAUMA",
  "MOTIVATIONAL_INTERVIEWING",
  "OCCUPATIONAL_THERAPY",
  "SPIRITUAL_SUPPORT",
  "PEER_SUPPORT",
];
const plan: Field[] = [
  note("presenting_problem", "Presenting problem", true, "Goals"),
  text("problem_area", "Diagnosis / problem area", true, "Goals"),
  note("goal", "Treatment goal", true, "Goals"),
  {
    name: "objectives",
    label: "Measurable objective",
    type: "array",
    required: true,
    section: "Objectives",
    fields: [
      note("description", "Objective", true),
      text("measure", "Measure", true),
      note("intervention", "Intervention", true),
      date("target_date", "Target date", true),
      note("outcome", "Outcome"),
      check("completed", "Objective completed"),
    ],
  },
  staff(
    "responsible_professional_id",
    "Responsible professional",
    true,
    "Review",
  ),
  date("start_date", "Start date", true, "Review"),
  date("target_date", "Target date", true, "Review"),
  date("review_date", "Review date", true, "Review"),
  choice(
    "status",
    "Plan state",
    ["DRAFT", "ACTIVE", "UNDER_REVIEW", "REVISED", "COMPLETED", "CANCELLED"],
    true,
    "DRAFT",
    "Review",
  ),
  note("outcome", "Plan outcome", false, "Review"),
];
const session: Field[] = [
  choice("session_type", "Session type", sessionTypes),
  staff("therapist_id", "Therapist", true),
  stamp("start_at", "Start time", true),
  stamp("end_at", "End time", true),
  note("objective", "Objective", true),
  choice("status", "Session state", [
    "SCHEDULED",
    "COMPLETED",
    "MISSED",
    "CANCELLED",
  ]),
  ...[
    "summary",
    "intervention",
    "client_response",
    "progress",
    "homework",
    "risk_concerns",
  ].map((n) => note(n, n.replaceAll("_", " "))),
  stamp("next_session", "Next session"),
  check("confidential", "Restricted psychotherapy note"),
];
const cases: Field[] = [
  staff("case_manager_id", "Case manager", true),
  staff("counsellor_id", "Counsellor", true),
  strings("team_member_ids", "Team member staff IDs"),
  date("assessment_due", "Assessment due"),
  date("family_meeting_due", "Family meeting due"),
  date("discharge_preparation_due", "Discharge preparation due"),
  note("notes", "Coordination notes"),
];
const revision = (fields: Field[], path: string, permission: string) => ({
  label: "Revise record",
  contextKeys: ["admission_id"],
  permission,
  path: () => path,
  fields: [
    ...fields,
    text("supersedes_id", "Previous record ID", true),
    note("correction_reason", "Revision reason", true),
  ],
  defaults: (r: { id: string }) => ({ supersedes_id: r.id }),
});
export const rehabResources: Resource[] = [
  {
    title: "Treatment plans",
    historyPath: (r) =>
      `/rehabilitation/treatment-plans?admission_id=${r.admission_id}&root_id=${r.root_id}&current_only=false`,
    path: "/rehabilitation/treatment-plans",
    permission: "treatment_plan.view",
    writePermission: "treatment_plan.manage",
    fields: plan,
    admissionScoped: true,
    columns: [
      { key: "problem_area", label: "Problem" },
      { key: "goal", label: "Goal" },
      { key: "review_date", label: "Review" },
      { key: "version", label: "Version" },
      { key: "status", label: "State" },
    ],
    actions: [
      revision(
        plan,
        "/rehabilitation/treatment-plans",
        "treatment_plan.manage",
      ),
    ],
  },
  {
    title: "Counselling sessions",
    path: "/rehabilitation/sessions",
    permission: "therapy.view",
    writePermission: "therapy.create_note",
    fields: session,
    admissionScoped: true,
    columns: [
      { key: "session_type", label: "Type" },
      { key: "start_at", label: "Session" },
      { key: "status", label: "State" },
      { key: "confidential", label: "Restricted" },
    ],
    actions: [
      revision(session, "/rehabilitation/sessions", "therapy.create_note"),
    ],
  },
  {
    title: "Case assignments",
    path: "/rehabilitation/cases",
    permission: "case_management.view",
    writePermission: "treatment_plan.manage",
    fields: cases,
    admissionScoped: true,
    columns: [
      { key: "case_manager_id", label: "Case manager" },
      { key: "assessment_due", label: "Assessment due" },
      { key: "family_meeting_due", label: "Family meeting" },
      { key: "discharge_preparation_due", label: "Discharge preparation" },
    ],
    actions: [
      revision(cases, "/rehabilitation/cases", "treatment_plan.manage"),
    ],
  },
  {
    title: "Assigned caseload",
    path: "/rehabilitation/case-dashboard",
    permission: "case_management.view",
    admissionScoped: true,
    columns: [
      { key: "client_name", label: "Client" },
      { key: "admission_number", label: "Admission" },
      { key: "assessment_overdue", label: "Assessment overdue" },
      { key: "missed_sessions", label: "Missed sessions" },
      { key: "active_risks", label: "Active risks" },
    ],
  },
  {
    title: "Group sessions",
    historyPath: (r) => `/rehabilitation/groups/${r.id}/attendance`,
    path: "/rehabilitation/groups",
    permission: "therapy.view",
    writePermission: "therapy.create_note",
    fields: [
      text("title", "Title", true),
      choice("session_type", "Session type", sessionTypes),
      text("topic", "Topic", true),
      staff("facilitator_id", "Facilitator", true),
      staff("co_facilitator_id", "Co-facilitator"),
      stamp("start_at", "Date and time", true),
      number("duration_minutes", "Duration (minutes)", true, 5, 720),
      text("location", "Location", true),
      note("objectives", "Objectives", true),
    ],
    columns: [
      { key: "title", label: "Group" },
      { key: "topic", label: "Topic" },
      { key: "start_at", label: "Date" },
      { key: "location", label: "Location" },
    ],
    actions: [
      {
        label: "Record participant attendance",
        permission: "therapy.create_note",
        path: (r) => `/rehabilitation/groups/${r.id}/attendance`,
        fields: [
          lookup("admission_id", "Participant admission", "/admissions"),
          choice("status", "Attendance", attendance),
          note("private_observation", "Restricted private observation"),
        ],
      },
    ],
  },
  {
    title: "Programme activities",
    historyPath: (r) => `/rehabilitation/programme/${r.id}/attendance`,
    path: "/rehabilitation/programme",
    permission: "programme.view",
    writePermission: "programme.manage",
    fields: [
      text("title", "Activity title", true),
      text("category", "Category", true),
      text("programme", "Programme (blank = all)"),
      stamp("start_at", "Start time", true),
      number("duration_minutes", "Duration", true, 5, 720),
      choice("recurrence", "Recurrence", ["ONCE", "DAILY", "WEEKLY"]),
      date("repeat_until", "Recurrence end"),
      text("location", "Location", true),
      staff("facilitator_id", "Facilitator", true),
    ],
    columns: [
      { key: "title", label: "Activity" },
      { key: "category", label: "Category" },
      { key: "start_at", label: "Starts" },
      { key: "recurrence", label: "Recurrence" },
    ],
    actions: [
      {
        label: "Record programme attendance",
        permission: "programme.manage",
        path: (r) => `/rehabilitation/programme/${r.id}/attendance`,
        fields: [
          lookup("admission_id", "Participant admission", "/admissions"),
          date("occurrence_date", "Occurrence date", true),
          choice("status", "Attendance", attendance),
          note("notes", "Notes"),
        ],
      },
    ],
  },
  {
    title: "Family intervention",
    path: "/rehabilitation/family-communications",
    permission: "family.view",
    writePermission: "family.record",
    admissionScoped: true,
    fields: [
      lookup(
        "consent_id",
        "Granted family consent",
        "/admissions/{admission_id}/consents",
        true,
        undefined,
        ["consent_type", "decision", "version"],
      ),
      lookup(
        "contact_id",
        "Authorised family contact",
        "/clients/{client_id}/contacts",
        true,
        undefined,
        ["name", "relationship"],
      ),
      stamp("communicated_at", "Communication time", true),
      choice("method", "Method", [
        "PHONE",
        "IN_PERSON",
        "VIDEO",
        "LETTER",
        "EMAIL",
      ]),
      note("purpose", "Purpose", true),
      note("shared_information", "Information shared", true),
      note("outcome", "Outcome"),
      date("next_meeting_date", "Next meeting"),
      check(
        "scope_confirmed",
        "I verified consent scope and information-sharing limits",
      ),
    ],
    columns: [
      { key: "communicated_at", label: "Date" },
      { key: "method", label: "Method" },
      { key: "purpose", label: "Purpose" },
      { key: "next_meeting_date", label: "Next meeting" },
    ],
  },
];
