import {
  check,
  choice,
  date,
  levels,
  lookup,
  note,
  number,
  staff,
  stamp,
  strings,
  text,
} from "../care/fields";
import type { Field, Resource } from "../care/types";

export const substanceFields: Field[] = [
  lookup(
    "substance_id",
    "Substance",
    "/rehabilitation/substances",
    true,
    "Substance",
  ),
  number("first_use_age", "Age at first use", false, 0, 120, "Substance"),
  number("regular_use_age", "Age at regular use", false, 0, 120, "Substance"),
  text("frequency", "Frequency", true, "Pattern"),
  text("quantity", "Quantity", true, "Pattern"),
  text("route", "Route", true, "Pattern"),
  text("duration", "Duration", false, "Pattern"),
  stamp("last_use", "Last use", false, "Pattern"),
  choice(
    "status",
    "Current use status",
    ["CURRENT", "ABSTINENT", "IN_REMISSION", "PAST"],
    true,
    "CURRENT",
    "Pattern",
  ),
  ...[
    "typical_pattern",
    "maximum_use",
    "withdrawal_symptoms",
    "tolerance",
    "overdose",
    "previous_quit_attempts",
    "previous_treatment",
    "consequences",
  ].map((n) =>
    note(n, n.replaceAll("_", " "), false, "History & consequences"),
  ),
  text(
    "longest_abstinence",
    "Longest abstinence",
    false,
    "History & consequences",
  ),
];
const sectionFields: Record<string, string[]> = {
  biological: [
    "health_history",
    "chronic_illness",
    "medication",
    "sleep",
    "nutrition",
    "disability",
    "physical_complaints",
  ],
  psychological: [
    "psychiatric_history",
    "mood",
    "anxiety",
    "trauma",
    "cognition",
    "suicide_risk",
    "self_harm",
    "previous_admissions",
  ],
  social: [
    "family",
    "relationships",
    "housing",
    "employment",
    "education",
    "finances",
    "peers",
    "support_systems",
  ],
  substance_use: [
    "history",
    "triggers",
    "consequences",
    "dependency_indicators",
  ],
  legal: ["court_cases", "probation", "legal_obligations"],
  occupational: ["skills", "work_history", "employability"],
  spiritual: ["appropriate_support"],
};
export const biopsyFields: Field[] = [
  choice("status", "Assessment state", ["DRAFT", "COMPLETED", "REVIEWED"]),
  ...Object.entries(sectionFields).map(([name, keys]): Field => ({
    name,
    label: name.replaceAll("_", " "),
    type: "object",
    section: name.replaceAll("_", " "),
    fields: keys.map((k) => note(k, k.replaceAll("_", " "))),
  })),
];
export const riskFields: Field[] = [
  choice("risk_type", "Risk type", [
    "SUICIDE",
    "SELF_HARM",
    "AGGRESSION",
    "VIOLENCE",
    "ABSCONDING",
    "RELAPSE",
    "OVERDOSE",
    "FALLS",
    "SEIZURE",
    "WITHDRAWAL_COMPLICATION",
    "EXPLOITATION",
    "ABUSE",
    "MEDICAL_DETERIORATION",
  ]),
  choice("level", "Risk level", levels),
  note("risk_factors", "Risk factors", true),
  note("protective_factors", "Protective factors"),
  note("intervention", "Intervention", true),
  staff("assigned_staff_id", "Responsible staff", true),
  date("review_date", "Review date", true),
  choice("status", "Risk status", ["ACTIVE", "RESOLVED"]),
];
const revision = (fields: Field[], path: string, permission: string) => ({
  label: "Revise record",
  contextKeys: ["admission_id"],
  permission,
  path: () => path,
  fields: [
    ...fields,
    text("supersedes_id", "Previous record ID", true),
    note("correction_reason", "Reason for revision", true),
  ],
  defaults: (record: { id: string }) => ({ supersedes_id: record.id }),
});
export const assessmentResources: Resource[] = [
  {
    title: "Substance catalogue",
    path: "/rehabilitation/substances",
    permission: "assessment.view",
    writePermission: "assessment.configure",
    fields: [
      text("name", "Substance name", true),
      check("active", "Active substance", undefined, true),
    ],
    columns: [
      { key: "name", label: "Substance" },
      { key: "active", label: "Active" },
    ],
  },
  {
    title: "Substance histories",
    path: "/rehabilitation/substance-histories",
    permission: "assessment.view",
    writePermission: "assessment.record",
    fields: substanceFields,
    admissionScoped: true,
    columns: [
      { key: "substance_id", label: "Substance" },
      { key: "frequency", label: "Frequency" },
      { key: "quantity", label: "Quantity" },
      { key: "last_use", label: "Last use" },
      { key: "status", label: "Status" },
    ],
    actions: [
      revision(
        substanceFields,
        "/rehabilitation/substance-histories",
        "assessment.record",
      ),
    ],
  },
  {
    title: "Biopsychosocial",
    path: "/rehabilitation/biopsychosocial",
    permission: "assessment.view",
    writePermission: "assessment.record",
    fields: biopsyFields,
    admissionScoped: true,
    columns: [
      { key: "created_at", label: "Recorded" },
      { key: "status", label: "State" },
      { key: "reviewed_by", label: "Reviewer" },
    ],
    actions: [
      revision(
        biopsyFields,
        "/rehabilitation/biopsychosocial",
        "assessment.record",
      ),
    ],
  },
  {
    title: "Risk assessments",
    path: "/rehabilitation/risks",
    permission: "risk.view",
    writePermission: "risk.record",
    fields: riskFields,
    admissionScoped: true,
    columns: [
      { key: "risk_type", label: "Risk" },
      { key: "level", label: "Level" },
      { key: "review_date", label: "Review due" },
      { key: "status", label: "Status" },
    ],
    actions: [revision(riskFields, "/rehabilitation/risks", "risk.record")],
  },
  {
    title: "High-risk alerts",
    path: "/rehabilitation/risk-alerts",
    permission: "risk.view",
    admissionScoped: true,
    columns: [
      { key: "risk_type", label: "Risk" },
      { key: "level", label: "Level" },
      { key: "review_date", label: "Review due" },
      { key: "intervention", label: "Intervention" },
    ],
  },
];
export const instrumentFields: Field[] = [
  text("code", "Instrument code (uppercase)", true),
  text("name", "Instrument name", true),
  note("instructions", "Instructions"),
  check("active", "Active instrument", undefined, true),
  {
    name: "questions",
    label: "Question",
    type: "array",
    required: true,
    section: "Questions",
    fields: [
      text("key", "Unique question key", true),
      note("text", "Question text", true),
      text("domain", "Score domain (optional)"),
      check("contributes_to_score", "Include in total", undefined, true),
      strings("alert_values", "Answers that flag a risk"),
      {
        name: "options",
        label: "Response option",
        type: "array",
        required: true,
        fields: [
          text("value", "Option value", true),
          text("label", "Option label", true),
          number("score", "Score", true, 0, 100),
        ],
      },
    ],
  },
  {
    name: "score_bands",
    label: "Score band",
    type: "array",
    required: true,
    section: "Interpretation",
    fields: [
      number("minimum", "Minimum", true, 0),
      number("maximum", "Maximum", true, 0),
      text("interpretation", "Interpretation", true),
      choice("risk_level", "Risk level", levels),
      text("domain", "Score domain (blank = total)"),
    ],
  },
];
export const instrumentResource: Resource = {
  title: "Instrument configuration",
  path: "/rehabilitation/instruments",
  permission: "assessment.view",
  writePermission: "assessment.configure",
  fields: instrumentFields,
  columns: [
    { key: "code", label: "Code" },
    { key: "name", label: "Instrument" },
    { key: "version", label: "Version" },
    { key: "active", label: "Active" },
  ],
  actions: [
    {
      label: "Create instrument version",
      permission: "assessment.configure",
      path: () => "/rehabilitation/instruments",
      fields: instrumentFields,
    },
  ],
};
