"""Scope audit events to facility

Revision ID: 395301858dbd
Revises: 9b420e3b6c10
"""

import sqlalchemy as sa
from alembic import op

revision = "395301858dbd"
down_revision = "9b420e3b6c10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_events", sa.Column("facility_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_audit_events_facility_id"), "audit_events", ["facility_id"], unique=False
    )
    op.create_foreign_key(
        "fk_audit_facility", "audit_events", "facilities", ["facility_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_audit_facility", "audit_events", type_="foreignkey")
    op.drop_index(op.f("ix_audit_events_facility_id"), table_name="audit_events")
    op.drop_column("audit_events", "facility_id")
    # ### end Alembic commands ###
