"""Phase 3 assessments treatment and rehabilitation

Revision ID: 4947cd5f55ab
Revises: 7e7f75ca5c6e
"""

import sqlalchemy as sa
from alembic import op

revision = "4947cd5f55ab"
down_revision = "7e7f75ca5c6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_instruments",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("score_bands", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "code", "version"),
    )
    op.create_index(
        op.f("ix_assessment_instruments_code"), "assessment_instruments", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_instruments_facility_id"),
        "assessment_instruments",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "rehab_substances",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "name"),
    )
    op.create_index(
        op.f("ix_rehab_substances_facility_id"), "rehab_substances", ["facility_id"], unique=False
    )
    op.create_table(
        "group_sessions",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("session_type", sa.String(length=70), nullable=False),
        sa.Column("topic", sa.String(length=300), nullable=False),
        sa.Column("facilitator_id", sa.Uuid(), nullable=False),
        sa.Column("co_facilitator_id", sa.Uuid(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("objectives", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["co_facilitator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facilitator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_sessions_facility_id"), "group_sessions", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_group_sessions_start_at"), "group_sessions", ["start_at"], unique=False
    )
    op.create_table(
        "programme_activities",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("programme", sa.String(length=150), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("recurrence", sa.String(length=10), nullable=False),
        sa.Column("repeat_until", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("facilitator_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facilitator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_programme_activities_facility_id"),
        "programme_activities",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_programme_activities_start_at"), "programme_activities", ["start_at"], unique=False
    )
    op.create_table(
        "biopsychosocial_assessments",
        sa.Column("biological", sa.JSON(), nullable=False),
        sa.Column("psychological", sa.JSON(), nullable=False),
        sa.Column("social", sa.JSON(), nullable=False),
        sa.Column("substance_use", sa.JSON(), nullable=False),
        sa.Column("legal", sa.JSON(), nullable=False),
        sa.Column("occupational", sa.JSON(), nullable=False),
        sa.Column("spiritual", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("status IN ('DRAFT','COMPLETED','REVIEWED')"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["biopsychosocial_assessments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_biopsychosocial_assessments_admission_id"),
        "biopsychosocial_assessments",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_biopsychosocial_assessments_facility_id"),
        "biopsychosocial_assessments",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "case_assignments",
        sa.Column("case_manager_id", sa.Uuid(), nullable=False),
        sa.Column("counsellor_id", sa.Uuid(), nullable=False),
        sa.Column("team_member_ids", sa.JSON(), nullable=False),
        sa.Column("assessment_due", sa.Date(), nullable=True),
        sa.Column("family_meeting_due", sa.Date(), nullable=True),
        sa.Column("discharge_preparation_due", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_manager_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["counsellor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["case_assignments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_case_assignments_admission_id"), "case_assignments", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_assignments_case_manager_id"),
        "case_assignments",
        ["case_manager_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_assignments_facility_id"), "case_assignments", ["facility_id"], unique=False
    )
    op.create_table(
        "group_attendances",
        sa.Column("group_session_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("private_observation", sa.Text(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("status IN ('PRESENT','ABSENT','EXCUSED','REFUSED','LATE')"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_session_id"],
            ["group_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["group_attendances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_group_attendances_admission_id"),
        "group_attendances",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_attendances_facility_id"), "group_attendances", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_group_attendances_group_session_id"),
        "group_attendances",
        ["group_session_id"],
        unique=False,
    )
    op.create_table(
        "instrument_assessments",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("domain_scores", sa.JSON(), nullable=False),
        sa.Column("interpretation", sa.String(length=500), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_by", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["assessment_instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instrument_assessments_admission_id"),
        "instrument_assessments",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_assessments_facility_id"),
        "instrument_assessments",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instrument_assessments_instrument_id"),
        "instrument_assessments",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "programme_attendances",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("status IN ('PRESENT','ABSENT','EXCUSED','REFUSED','LATE')"),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["programme_activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["programme_attendances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_programme_attendances_activity_id"),
        "programme_attendances",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_programme_attendances_admission_id"),
        "programme_attendances",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_programme_attendances_facility_id"),
        "programme_attendances",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_programme_attendances_occurrence_date"),
        "programme_attendances",
        ["occurrence_date"],
        unique=False,
    )
    op.create_table(
        "risk_assessments",
        sa.Column("risk_type", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("risk_factors", sa.Text(), nullable=False),
        sa.Column("protective_factors", sa.Text(), nullable=False),
        sa.Column("intervention", sa.Text(), nullable=False),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=False),
        sa.Column("review_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("level IN ('LOW','MODERATE','HIGH','CRITICAL')"),
        sa.CheckConstraint("status IN ('ACTIVE','RESOLVED')"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["risk_assessments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_risk_assessments_admission_id"), "risk_assessments", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_risk_assessments_assigned_staff_id"),
        "risk_assessments",
        ["assigned_staff_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_assessments_facility_id"), "risk_assessments", ["facility_id"], unique=False
    )
    op.create_index(op.f("ix_risk_assessments_level"), "risk_assessments", ["level"], unique=False)
    op.create_index(
        op.f("ix_risk_assessments_review_date"), "risk_assessments", ["review_date"], unique=False
    )
    op.create_index(
        op.f("ix_risk_assessments_risk_type"), "risk_assessments", ["risk_type"], unique=False
    )
    op.create_table(
        "substance_histories",
        sa.Column("substance_id", sa.Uuid(), nullable=False),
        sa.Column("first_use_age", sa.Integer(), nullable=True),
        sa.Column("regular_use_age", sa.Integer(), nullable=True),
        sa.Column("frequency", sa.String(length=150), nullable=False),
        sa.Column("quantity", sa.String(length=150), nullable=False),
        sa.Column("route", sa.String(length=100), nullable=False),
        sa.Column("duration", sa.String(length=150), nullable=False),
        sa.Column("last_use", sa.DateTime(timezone=True), nullable=True),
        sa.Column("typical_pattern", sa.Text(), nullable=False),
        sa.Column("maximum_use", sa.Text(), nullable=False),
        sa.Column("withdrawal_symptoms", sa.Text(), nullable=False),
        sa.Column("tolerance", sa.Text(), nullable=False),
        sa.Column("overdose", sa.Text(), nullable=False),
        sa.Column("previous_quit_attempts", sa.Text(), nullable=False),
        sa.Column("longest_abstinence", sa.String(length=150), nullable=False),
        sa.Column("previous_treatment", sa.Text(), nullable=False),
        sa.Column("consequences", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("first_use_age >= 0 AND first_use_age <= 120"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["substance_id"],
            ["rehab_substances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["substance_histories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_substance_histories_admission_id"),
        "substance_histories",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_substance_histories_facility_id"),
        "substance_histories",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_substance_histories_substance_id"),
        "substance_histories",
        ["substance_id"],
        unique=False,
    )
    op.create_table(
        "therapy_sessions",
        sa.Column("session_type", sa.String(length=70), nullable=False),
        sa.Column("therapist_id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("intervention", sa.Text(), nullable=False),
        sa.Column("client_response", sa.Text(), nullable=False),
        sa.Column("progress", sa.Text(), nullable=False),
        sa.Column("homework", sa.Text(), nullable=False),
        sa.Column("risk_concerns", sa.Text(), nullable=False),
        sa.Column("next_session", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidential", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("status IN ('SCHEDULED','COMPLETED','MISSED','CANCELLED')"),
        sa.CheckConstraint("end_at > start_at"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["therapy_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_therapy_sessions_admission_id"), "therapy_sessions", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_therapy_sessions_confidential"), "therapy_sessions", ["confidential"], unique=False
    )
    op.create_index(
        op.f("ix_therapy_sessions_facility_id"), "therapy_sessions", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_therapy_sessions_start_at"), "therapy_sessions", ["start_at"], unique=False
    )
    op.create_index(
        op.f("ix_therapy_sessions_therapist_id"), "therapy_sessions", ["therapist_id"], unique=False
    )
    op.create_table(
        "treatment_plans",
        sa.Column("root_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("presenting_problem", sa.Text(), nullable=False),
        sa.Column("problem_area", sa.String(length=300), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("objectives", sa.JSON(), nullable=False),
        sa.Column("responsible_professional_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("review_date", sa.Date(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','UNDER_REVIEW','REVISED','COMPLETED','CANCELLED')"
        ),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_professional_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["treatment_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supersedes_id"),
    )
    op.create_index(
        op.f("ix_treatment_plans_admission_id"), "treatment_plans", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_treatment_plans_facility_id"), "treatment_plans", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_treatment_plans_review_date"), "treatment_plans", ["review_date"], unique=False
    )
    op.create_index(
        op.f("ix_treatment_plans_root_id"), "treatment_plans", ["root_id"], unique=False
    )
    op.create_table(
        "family_communications",
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("communicated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("shared_information", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("next_meeting_date", sa.Date(), nullable=True),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["client_contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_family_communications_admission_id"),
        "family_communications",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_communications_consent_id"),
        "family_communications",
        ["consent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_communications_facility_id"),
        "family_communications",
        ["facility_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_family_communications_facility_id"), table_name="family_communications")
    op.drop_index(op.f("ix_family_communications_consent_id"), table_name="family_communications")
    op.drop_index(op.f("ix_family_communications_admission_id"), table_name="family_communications")
    op.drop_table("family_communications")
    op.drop_index(op.f("ix_treatment_plans_root_id"), table_name="treatment_plans")
    op.drop_index(op.f("ix_treatment_plans_review_date"), table_name="treatment_plans")
    op.drop_index(op.f("ix_treatment_plans_facility_id"), table_name="treatment_plans")
    op.drop_index(op.f("ix_treatment_plans_admission_id"), table_name="treatment_plans")
    op.drop_table("treatment_plans")
    op.drop_index(op.f("ix_therapy_sessions_therapist_id"), table_name="therapy_sessions")
    op.drop_index(op.f("ix_therapy_sessions_start_at"), table_name="therapy_sessions")
    op.drop_index(op.f("ix_therapy_sessions_facility_id"), table_name="therapy_sessions")
    op.drop_index(op.f("ix_therapy_sessions_confidential"), table_name="therapy_sessions")
    op.drop_index(op.f("ix_therapy_sessions_admission_id"), table_name="therapy_sessions")
    op.drop_table("therapy_sessions")
    op.drop_index(op.f("ix_substance_histories_substance_id"), table_name="substance_histories")
    op.drop_index(op.f("ix_substance_histories_facility_id"), table_name="substance_histories")
    op.drop_index(op.f("ix_substance_histories_admission_id"), table_name="substance_histories")
    op.drop_table("substance_histories")
    op.drop_index(op.f("ix_risk_assessments_risk_type"), table_name="risk_assessments")
    op.drop_index(op.f("ix_risk_assessments_review_date"), table_name="risk_assessments")
    op.drop_index(op.f("ix_risk_assessments_level"), table_name="risk_assessments")
    op.drop_index(op.f("ix_risk_assessments_facility_id"), table_name="risk_assessments")
    op.drop_index(op.f("ix_risk_assessments_assigned_staff_id"), table_name="risk_assessments")
    op.drop_index(op.f("ix_risk_assessments_admission_id"), table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_index(
        op.f("ix_programme_attendances_occurrence_date"), table_name="programme_attendances"
    )
    op.drop_index(op.f("ix_programme_attendances_facility_id"), table_name="programme_attendances")
    op.drop_index(op.f("ix_programme_attendances_admission_id"), table_name="programme_attendances")
    op.drop_index(op.f("ix_programme_attendances_activity_id"), table_name="programme_attendances")
    op.drop_table("programme_attendances")
    op.drop_index(
        op.f("ix_instrument_assessments_instrument_id"), table_name="instrument_assessments"
    )
    op.drop_index(
        op.f("ix_instrument_assessments_facility_id"), table_name="instrument_assessments"
    )
    op.drop_index(
        op.f("ix_instrument_assessments_admission_id"), table_name="instrument_assessments"
    )
    op.drop_table("instrument_assessments")
    op.drop_index(op.f("ix_group_attendances_group_session_id"), table_name="group_attendances")
    op.drop_index(op.f("ix_group_attendances_facility_id"), table_name="group_attendances")
    op.drop_index(op.f("ix_group_attendances_admission_id"), table_name="group_attendances")
    op.drop_table("group_attendances")
    op.drop_index(op.f("ix_case_assignments_facility_id"), table_name="case_assignments")
    op.drop_index(op.f("ix_case_assignments_case_manager_id"), table_name="case_assignments")
    op.drop_index(op.f("ix_case_assignments_admission_id"), table_name="case_assignments")
    op.drop_table("case_assignments")
    op.drop_index(
        op.f("ix_biopsychosocial_assessments_facility_id"), table_name="biopsychosocial_assessments"
    )
    op.drop_index(
        op.f("ix_biopsychosocial_assessments_admission_id"),
        table_name="biopsychosocial_assessments",
    )
    op.drop_table("biopsychosocial_assessments")
    op.drop_index(op.f("ix_programme_activities_start_at"), table_name="programme_activities")
    op.drop_index(op.f("ix_programme_activities_facility_id"), table_name="programme_activities")
    op.drop_table("programme_activities")
    op.drop_index(op.f("ix_group_sessions_start_at"), table_name="group_sessions")
    op.drop_index(op.f("ix_group_sessions_facility_id"), table_name="group_sessions")
    op.drop_table("group_sessions")
    op.drop_index(op.f("ix_rehab_substances_facility_id"), table_name="rehab_substances")
    op.drop_table("rehab_substances")
    op.drop_index(
        op.f("ix_assessment_instruments_facility_id"), table_name="assessment_instruments"
    )
    op.drop_index(op.f("ix_assessment_instruments_code"), table_name="assessment_instruments")
    op.drop_table("assessment_instruments")
    # ### end Alembic commands ###
