"""Phase 5 prescriptions eMAR and pharmacy

Revision ID: 6b7fa2fc9da8
Revises: d0846c43e92e
"""

import sqlalchemy as sa
from alembic import op

revision = "6b7fa2fc9da8"
down_revision = "d0846c43e92e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medication_routes",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "medications",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("generic_name", sa.String(length=150), nullable=False),
        sa.Column("brand_name", sa.String(length=150), nullable=True),
        sa.Column("formulation", sa.String(length=100), nullable=False),
        sa.Column("strength", sa.String(length=100), nullable=False),
        sa.Column("dose_unit", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("reorder_level", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("reorder_level >= 0", name="ck_medication_reorder"),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "facility_id", "generic_name", "strength", "formulation", name="uq_medication_catalogue"
        ),
    )
    op.create_index(
        op.f("ix_medications_facility_id"), "medications", ["facility_id"], unique=False
    )
    op.create_table(
        "pharmacy_suppliers",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pharmacy_suppliers_facility_id"),
        "pharmacy_suppliers",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "drug_batches",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("batch_number", sa.String(length=100), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("receipt_reference", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("quantity >= 0", name="ck_batch_quantity"),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["pharmacy_suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "medication_id", "batch_number", name="uq_drug_batch"),
    )
    op.create_index(
        op.f("ix_drug_batches_expiry_date"), "drug_batches", ["expiry_date"], unique=False
    )
    op.create_index(
        op.f("ix_drug_batches_facility_id"), "drug_batches", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_drug_batches_medication_id"), "drug_batches", ["medication_id"], unique=False
    )
    op.create_table(
        "ward_stock",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("quantity >= 0", name="ck_ward_quantity"),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["drug_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "location", name="uq_ward_batch"),
    )
    op.create_index(op.f("ix_ward_stock_batch_id"), "ward_stock", ["batch_id"], unique=False)
    op.create_index(op.f("ix_ward_stock_facility_id"), "ward_stock", ["facility_id"], unique=False)
    op.create_table(
        "prescriptions",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column("generic_name", sa.String(length=150), nullable=False),
        sa.Column("brand_name", sa.String(length=150), nullable=True),
        sa.Column("formulation", sa.String(length=100), nullable=False),
        sa.Column("strength", sa.String(length=100), nullable=False),
        sa.Column("dose", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("dose_unit", sa.String(length=30), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("frequency", sa.String(length=100), nullable=False),
        sa.Column("frequency_hours", sa.Integer(), nullable=True),
        sa.Column("scheduled_times", sa.JSON(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stop_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prn", sa.Boolean(), nullable=False),
        sa.Column("indication", sa.String(length=500), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("allergy_override_reason", sa.String(length=500), nullable=True),
        sa.Column("prn_min_interval_hours", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("prescriber_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','SUSPENDED','DISCONTINUED','COMPLETED')",
            name="ck_prescription_status",
        ),
        sa.CheckConstraint("dose > 0", name="ck_prescription_dose"),
        sa.CheckConstraint(
            "frequency_hours IS NULL OR frequency_hours > 0", name="ck_prescription_frequency"
        ),
        sa.CheckConstraint("stop_at IS NULL OR stop_at > start_at", name="ck_prescription_dates"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescriber_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["medication_routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescriptions_admission_id"), "prescriptions", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_client_id"), "prescriptions", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_facility_id"), "prescriptions", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_medication_id"), "prescriptions", ["medication_id"], unique=False
    )
    op.create_index(op.f("ix_prescriptions_start_at"), "prescriptions", ["start_at"], unique=False)
    op.create_index(op.f("ix_prescriptions_status"), "prescriptions", ["status"], unique=False)
    op.create_table(
        "medication_doses",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_version", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prescribed_dose", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("dose_unit", sa.String(length=30), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cancelled_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["medication_routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prescription_id", "prescription_version", "scheduled_at", name="uq_scheduled_dose"
        ),
    )
    op.create_index(
        op.f("ix_medication_doses_admission_id"), "medication_doses", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_medication_doses_facility_id"), "medication_doses", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_medication_doses_prescription_id"),
        "medication_doses",
        ["prescription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_doses_scheduled_at"), "medication_doses", ["scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_medication_doses_status"), "medication_doses", ["status"], unique=False
    )
    op.create_table(
        "pharmacy_movements",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=True),
        sa.Column("movement_type", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("resulting_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("quantity > 0", name="ck_movement_quantity"),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["drug_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pharmacy_movements_batch_id"), "pharmacy_movements", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_pharmacy_movements_facility_id"),
        "pharmacy_movements",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_movements_movement_type"),
        "pharmacy_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_movements_prescription_id"),
        "pharmacy_movements",
        ["prescription_id"],
        unique=False,
    )
    op.create_table(
        "prescription_revisions",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prescription_id", "version", name="uq_prescription_revision"),
    )
    op.create_index(
        op.f("ix_prescription_revisions_facility_id"),
        "prescription_revisions",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescription_revisions_prescription_id"),
        "prescription_revisions",
        ["prescription_id"],
        unique=False,
    )
    op.create_table(
        "medication_administrations",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_version", sa.Integer(), nullable=False),
        sa.Column("dose_id", sa.Uuid(), nullable=True),
        sa.Column("prescribed_dose", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("actual_dose", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("dose_unit", sa.String(length=30), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("administered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("administered_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('GIVEN','REFUSED','OMITTED','HELD','NOT_AVAILABLE','PATIENT_AWAY','PRN')",
            name="ck_administration_status",
        ),
        sa.CheckConstraint("actual_dose IS NULL OR actual_dose >= 0", name="ck_actual_dose"),
        sa.ForeignKeyConstraint(
            ["administered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dose_id"],
            ["medication_doses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["medication_routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dose_id", name="uq_dose_administration"),
    )
    op.create_index(
        op.f("ix_medication_administrations_administered_at"),
        "medication_administrations",
        ["administered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_admission_id"),
        "medication_administrations",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_client_id"),
        "medication_administrations",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_dose_id"),
        "medication_administrations",
        ["dose_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_facility_id"),
        "medication_administrations",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_prescription_id"),
        "medication_administrations",
        ["prescription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_status"),
        "medication_administrations",
        ["status"],
        unique=False,
    )
    op.create_table(
        "administration_addenda",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("administration_id", sa.Uuid(), nullable=False),
        sa.Column("correction", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["administration_id"],
            ["medication_administrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_administration_addenda_administration_id"),
        "administration_addenda",
        ["administration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_administration_addenda_facility_id"),
        "administration_addenda",
        ["facility_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_administration_addenda_facility_id"), table_name="administration_addenda"
    )
    op.drop_index(
        op.f("ix_administration_addenda_administration_id"), table_name="administration_addenda"
    )
    op.drop_table("administration_addenda")
    op.drop_index(
        op.f("ix_medication_administrations_status"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_prescription_id"),
        table_name="medication_administrations",
    )
    op.drop_index(
        op.f("ix_medication_administrations_facility_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_dose_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_client_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_admission_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_administered_at"),
        table_name="medication_administrations",
    )
    op.drop_table("medication_administrations")
    op.drop_index(
        op.f("ix_prescription_revisions_prescription_id"), table_name="prescription_revisions"
    )
    op.drop_index(
        op.f("ix_prescription_revisions_facility_id"), table_name="prescription_revisions"
    )
    op.drop_table("prescription_revisions")
    op.drop_index(op.f("ix_pharmacy_movements_prescription_id"), table_name="pharmacy_movements")
    op.drop_index(op.f("ix_pharmacy_movements_movement_type"), table_name="pharmacy_movements")
    op.drop_index(op.f("ix_pharmacy_movements_facility_id"), table_name="pharmacy_movements")
    op.drop_index(op.f("ix_pharmacy_movements_batch_id"), table_name="pharmacy_movements")
    op.drop_table("pharmacy_movements")
    op.drop_index(op.f("ix_medication_doses_status"), table_name="medication_doses")
    op.drop_index(op.f("ix_medication_doses_scheduled_at"), table_name="medication_doses")
    op.drop_index(op.f("ix_medication_doses_prescription_id"), table_name="medication_doses")
    op.drop_index(op.f("ix_medication_doses_facility_id"), table_name="medication_doses")
    op.drop_index(op.f("ix_medication_doses_admission_id"), table_name="medication_doses")
    op.drop_table("medication_doses")
    op.drop_index(op.f("ix_prescriptions_status"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_start_at"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_medication_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_facility_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_client_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_admission_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_ward_stock_facility_id"), table_name="ward_stock")
    op.drop_index(op.f("ix_ward_stock_batch_id"), table_name="ward_stock")
    op.drop_table("ward_stock")
    op.drop_index(op.f("ix_drug_batches_medication_id"), table_name="drug_batches")
    op.drop_index(op.f("ix_drug_batches_facility_id"), table_name="drug_batches")
    op.drop_index(op.f("ix_drug_batches_expiry_date"), table_name="drug_batches")
    op.drop_table("drug_batches")
    op.drop_index(op.f("ix_pharmacy_suppliers_facility_id"), table_name="pharmacy_suppliers")
    op.drop_table("pharmacy_suppliers")
    op.drop_index(op.f("ix_medications_facility_id"), table_name="medications")
    op.drop_table("medications")
    op.drop_table("medication_routes")
    # ### end Alembic commands ###
