"""Phase 2 master client intake and residential care

Revision ID: 7e7f75ca5c6e
Revises: 395301858dbd
"""

import sqlalchemy as sa
from alembic import op

revision = "7e7f75ca5c6e"
down_revision = "395301858dbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("client_number", sa.String(length=40), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(length=30), nullable=False),
        sa.Column("marital_status", sa.String(length=30), nullable=True),
        sa.Column("nationality", sa.String(length=80), nullable=False),
        sa.Column("national_id", sa.String(length=40), nullable=True),
        sa.Column("passport_number", sa.String(length=40), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("county", sa.String(length=80), nullable=True),
        sa.Column("sub_county", sa.String(length=80), nullable=True),
        sa.Column("ward", sa.String(length=80), nullable=True),
        sa.Column("physical_address", sa.Text(), nullable=True),
        sa.Column("occupation", sa.String(length=150), nullable=True),
        sa.Column("employer", sa.String(length=150), nullable=True),
        sa.Column("religion", sa.String(length=100), nullable=True),
        sa.Column("religion_consent", sa.Boolean(), nullable=False),
        sa.Column("religion_policy_required", sa.Boolean(), nullable=False),
        sa.Column("referring_institution", sa.String(length=200), nullable=True),
        sa.Column("photo_reference", sa.String(length=300), nullable=True),
        sa.Column("allergies", sa.JSON(), nullable=False),
        sa.Column("chronic_conditions", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deceased", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "client_number"),
        sa.UniqueConstraint("facility_id", "national_id"),
        sa.UniqueConstraint("facility_id", "passport_number"),
    )
    op.create_index(op.f("ix_clients_client_number"), "clients", ["client_number"], unique=False)
    op.create_index(op.f("ix_clients_facility_id"), "clients", ["facility_id"], unique=False)
    op.create_index(op.f("ix_clients_national_id"), "clients", ["national_id"], unique=False)
    op.create_index(op.f("ix_clients_phone"), "clients", ["phone"], unique=False)
    op.create_index(op.f("ix_clients_surname"), "clients", ["surname"], unique=False)
    op.create_table(
        "record_numbers",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("facility_id", "kind", "year"),
    )
    op.create_table(
        "reference_seeds",
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "domain", "version", name="uq_reference_seed"),
    )
    op.create_index(
        op.f("ix_reference_seeds_facility_id"), "reference_seeds", ["facility_id"], unique=False
    )
    op.create_table(
        "wings",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "name"),
    )
    op.create_index(op.f("ix_wings_facility_id"), "wings", ["facility_id"], unique=False)
    op.create_table(
        "client_contacts",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("relationship", sa.String(length=80), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("authorized_contact", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_contacts_client_id"), "client_contacts", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_contacts_facility_id"), "client_contacts", ["facility_id"], unique=False
    )
    op.create_table(
        "referrals",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("referral_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("referring_person", sa.String(length=150), nullable=True),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("presenting_problem", sa.Text(), nullable=False),
        sa.Column("urgency", sa.String(length=20), nullable=False),
        sa.Column("pre_admission_notes", sa.Text(), nullable=True),
        sa.Column("documents", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrals_client_id"), "referrals", ["client_id"], unique=False)
    op.create_index(op.f("ix_referrals_facility_id"), "referrals", ["facility_id"], unique=False)
    op.create_index(op.f("ix_referrals_status"), "referrals", ["status"], unique=False)
    op.create_table(
        "rooms",
        sa.Column("wing_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sex_restriction", sa.String(length=30), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wing_id"],
            ["wings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "name"),
    )
    op.create_index(op.f("ix_rooms_facility_id"), "rooms", ["facility_id"], unique=False)
    op.create_index(op.f("ix_rooms_wing_id"), "rooms", ["wing_id"], unique=False)
    op.create_table(
        "admissions",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("referral_id", sa.Uuid(), nullable=True),
        sa.Column("admission_number", sa.String(length=40), nullable=False),
        sa.Column("admission_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admission_type", sa.String(length=30), nullable=False),
        sa.Column("accompanying_person", sa.String(length=150), nullable=True),
        sa.Column("referring_organization", sa.String(length=200), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("programme", sa.String(length=150), nullable=False),
        sa.Column("expected_duration_days", sa.Integer(), nullable=False),
        sa.Column("expected_discharge_date", sa.Date(), nullable=True),
        sa.Column("assigned_counsellor_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_clinician_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_nurse_id", sa.Uuid(), nullable=True),
        sa.Column("primary_case_manager_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("client_rights_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("treatment_agreement", sa.Boolean(), nullable=False),
        sa.Column("visitor_permissions", sa.Text(), nullable=True),
        sa.Column("communication_permissions", sa.Text(), nullable=True),
        sa.Column("dietary_requirements", sa.Text(), nullable=True),
        sa.Column("allergies", sa.JSON(), nullable=False),
        sa.Column("risk_flags", sa.JSON(), nullable=False),
        sa.Column("search_permitted", sa.Boolean(), nullable=False),
        sa.Column("search_record", sa.Text(), nullable=True),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("expected_duration_days > 0", name="admission_duration_positive"),
        sa.ForeignKeyConstraint(
            ["assigned_clinician_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_counsellor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_nurse_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_case_manager_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["referrals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "admission_number"),
        sa.UniqueConstraint("referral_id"),
    )
    op.create_index(
        op.f("ix_admissions_admission_date"), "admissions", ["admission_date"], unique=False
    )
    op.create_index(
        op.f("ix_admissions_admission_number"), "admissions", ["admission_number"], unique=False
    )
    op.create_index(op.f("ix_admissions_client_id"), "admissions", ["client_id"], unique=False)
    op.create_index(op.f("ix_admissions_facility_id"), "admissions", ["facility_id"], unique=False)
    op.create_index(op.f("ix_admissions_status"), "admissions", ["status"], unique=False)
    op.create_index(
        "uq_client_open_admission",
        "admissions",
        ["facility_id", "client_id"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('DISCHARGED','TRANSFERRED','DECEASED')"),
        sqlite_where=sa.text("status NOT IN ('DISCHARGED','TRANSFERRED','DECEASED')"),
    )
    op.create_table(
        "beds",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('AVAILABLE','OCCUPIED','RESERVED','CLEANING','MAINTENANCE','UNAVAILABLE')",
            name="bed_valid_status",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "name"),
    )
    op.create_index(op.f("ix_beds_facility_id"), "beds", ["facility_id"], unique=False)
    op.create_index(op.f("ix_beds_room_id"), "beds", ["room_id"], unique=False)
    op.create_index(op.f("ix_beds_status"), "beds", ["status"], unique=False)
    op.create_table(
        "pre_admission_screenings",
        sa.Column("referral_id", sa.Uuid(), nullable=False),
        sa.Column("current_intoxication", sa.Boolean(), nullable=False),
        sa.Column("withdrawal_risk", sa.String(length=20), nullable=False),
        sa.Column("suicide_risk", sa.String(length=20), nullable=False),
        sa.Column("self_harm_risk", sa.String(length=20), nullable=False),
        sa.Column("violence_risk", sa.String(length=20), nullable=False),
        sa.Column("psychosis", sa.Boolean(), nullable=False),
        sa.Column("severe_medical_condition", sa.Boolean(), nullable=False),
        sa.Column("pregnancy", sa.Boolean(), nullable=False),
        sa.Column("seizure_history", sa.Boolean(), nullable=False),
        sa.Column("overdose_history", sa.Boolean(), nullable=False),
        sa.Column("current_medication", sa.Text(), nullable=True),
        sa.Column("communicable_disease_concerns", sa.Text(), nullable=True),
        sa.Column("accommodation_suitable", sa.Boolean(), nullable=False),
        sa.Column("clinically_suitable", sa.Boolean(), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("screened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["referrals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pre_admission_screenings_facility_id"),
        "pre_admission_screenings",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pre_admission_screenings_referral_id"),
        "pre_admission_screenings",
        ["referral_id"],
        unique=False,
    )
    op.create_table(
        "admission_property",
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("storage_location", sa.String(length=150), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_by", sa.Uuid(), nullable=False),
        sa.Column("returned_by", sa.Uuid(), nullable=True),
        sa.Column("return_reason", sa.Text(), nullable=True),
        sa.Column("client_acknowledgment", sa.String(length=150), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("quantity > 0", name="property_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["received_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["returned_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admission_property_admission_id"),
        "admission_property",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_property_facility_id"),
        "admission_property",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "admission_status_history",
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=30), nullable=False),
        sa.Column("new_status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admission_status_history_admission_id"),
        "admission_status_history",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_status_history_facility_id"),
        "admission_status_history",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "bed_assignments",
        sa.Column("bed_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bed_id"],
            ["beds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bed_assignments_admission_id"), "bed_assignments", ["admission_id"], unique=False
    )
    op.create_index(op.f("ix_bed_assignments_bed_id"), "bed_assignments", ["bed_id"], unique=False)
    op.create_index(
        op.f("ix_bed_assignments_facility_id"), "bed_assignments", ["facility_id"], unique=False
    )
    op.create_index(
        "uq_admission_active_bed",
        "bed_assignments",
        ["admission_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
        sqlite_where=sa.text("ended_at IS NULL"),
    )
    op.create_index(
        "uq_bed_active_assignment",
        "bed_assignments",
        ["bed_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
        sqlite_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "consents",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("consent_type", sa.String(length=40), nullable=False),
        sa.Column("consent_text", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("consent_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawal_reason", sa.Text(), nullable=True),
        sa.Column("witness", sa.String(length=150), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("decision IN ('GRANTED','DECLINED')", name="consent_valid_decision"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consents_admission_id"), "consents", ["admission_id"], unique=False)
    op.create_index(op.f("ix_consents_client_id"), "consents", ["client_id"], unique=False)
    op.create_index(op.f("ix_consents_facility_id"), "consents", ["facility_id"], unique=False)
    op.create_table(
        "episodes_of_care",
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admission_id"),
    )
    op.create_index(
        op.f("ix_episodes_of_care_client_id"), "episodes_of_care", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_episodes_of_care_facility_id"), "episodes_of_care", ["facility_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_episodes_of_care_facility_id"), table_name="episodes_of_care")
    op.drop_index(op.f("ix_episodes_of_care_client_id"), table_name="episodes_of_care")
    op.drop_table("episodes_of_care")
    op.drop_index(op.f("ix_consents_facility_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_client_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_admission_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(
        "uq_bed_active_assignment",
        table_name="bed_assignments",
        postgresql_where=sa.text("ended_at IS NULL"),
        sqlite_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(
        "uq_admission_active_bed",
        table_name="bed_assignments",
        postgresql_where=sa.text("ended_at IS NULL"),
        sqlite_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(op.f("ix_bed_assignments_facility_id"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_bed_id"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_admission_id"), table_name="bed_assignments")
    op.drop_table("bed_assignments")
    op.drop_index(
        op.f("ix_admission_status_history_facility_id"), table_name="admission_status_history"
    )
    op.drop_index(
        op.f("ix_admission_status_history_admission_id"), table_name="admission_status_history"
    )
    op.drop_table("admission_status_history")
    op.drop_index(op.f("ix_admission_property_facility_id"), table_name="admission_property")
    op.drop_index(op.f("ix_admission_property_admission_id"), table_name="admission_property")
    op.drop_table("admission_property")
    op.drop_index(
        op.f("ix_pre_admission_screenings_referral_id"), table_name="pre_admission_screenings"
    )
    op.drop_index(
        op.f("ix_pre_admission_screenings_facility_id"), table_name="pre_admission_screenings"
    )
    op.drop_table("pre_admission_screenings")
    op.drop_index(op.f("ix_beds_status"), table_name="beds")
    op.drop_index(op.f("ix_beds_room_id"), table_name="beds")
    op.drop_index(op.f("ix_beds_facility_id"), table_name="beds")
    op.drop_table("beds")
    op.drop_index(
        "uq_client_open_admission",
        table_name="admissions",
        postgresql_where=sa.text("status NOT IN ('DISCHARGED','TRANSFERRED','DECEASED')"),
        sqlite_where=sa.text("status NOT IN ('DISCHARGED','TRANSFERRED','DECEASED')"),
    )
    op.drop_index(op.f("ix_admissions_status"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_facility_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_client_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_admission_number"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_admission_date"), table_name="admissions")
    op.drop_table("admissions")
    op.drop_index(op.f("ix_rooms_wing_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_facility_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_referrals_status"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_facility_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_client_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_client_contacts_facility_id"), table_name="client_contacts")
    op.drop_index(op.f("ix_client_contacts_client_id"), table_name="client_contacts")
    op.drop_table("client_contacts")
    op.drop_index(op.f("ix_wings_facility_id"), table_name="wings")
    op.drop_table("wings")
    op.drop_index(op.f("ix_reference_seeds_facility_id"), table_name="reference_seeds")
    op.drop_table("reference_seeds")
    op.drop_table("record_numbers")
    op.drop_index(op.f("ix_clients_surname"), table_name="clients")
    op.drop_index(op.f("ix_clients_phone"), table_name="clients")
    op.drop_index(op.f("ix_clients_national_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_facility_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_client_number"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
