"""Admission intake amendment history

Revision ID: 942eea8cbd56
Revises: 45ec2a926701
"""

import sqlalchemy as sa
from alembic import op

revision = "942eea8cbd56"
down_revision = "45ec2a926701"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admission_intake_revisions",
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admission_id", "version", name="uq_admission_intake_revision"),
    )
    op.create_index(
        op.f("ix_admission_intake_revisions_admission_id"),
        "admission_intake_revisions",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_intake_revisions_facility_id"),
        "admission_intake_revisions",
        ["facility_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_admission_intake_revisions_facility_id"), table_name="admission_intake_revisions"
    )
    op.drop_index(
        op.f("ix_admission_intake_revisions_admission_id"), table_name="admission_intake_revisions"
    )
    op.drop_table("admission_intake_revisions")
    # ### end Alembic commands ###
