"""Private intake documents and client revision history

Revision ID: c109267ec439
Revises: 6b7fa2fc9da8
"""

import sqlalchemy as sa
from alembic import op

revision = "c109267ec439"
down_revision = "6b7fa2fc9da8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_revisions",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_revisions_client_id"), "client_revisions", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_revisions_facility_id"), "client_revisions", ["facility_id"], unique=False
    )
    op.create_table(
        "intake_documents",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("referral_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("filename", sa.String(length=150), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("confidentiality", sa.String(length=30), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["referrals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intake_documents_client_id"), "intake_documents", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_intake_documents_facility_id"), "intake_documents", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_intake_documents_referral_id"), "intake_documents", ["referral_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intake_documents_referral_id"), table_name="intake_documents")
    op.drop_index(op.f("ix_intake_documents_facility_id"), table_name="intake_documents")
    op.drop_index(op.f("ix_intake_documents_client_id"), table_name="intake_documents")
    op.drop_table("intake_documents")
    op.drop_index(op.f("ix_client_revisions_facility_id"), table_name="client_revisions")
    op.drop_index(op.f("ix_client_revisions_client_id"), table_name="client_revisions")
    op.drop_table("client_revisions")
    # ### end Alembic commands ###
