"""Phase 4 clinical nursing and investigations

Revision ID: d0846c43e92e
Revises: 4947cd5f55ab
"""

import sqlalchemy as sa
from alembic import op

revision = "d0846c43e92e"
down_revision = "4947cd5f55ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_note_revisions",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type", "entity_id", "version", name="uq_clinical_revision_version"
        ),
    )
    op.create_index(
        op.f("ix_clinical_note_revisions_entity_id"),
        "clinical_note_revisions",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_note_revisions_facility_id"),
        "clinical_note_revisions",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "clinical_allergies",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("substance", sa.String(length=200), nullable=False),
        sa.Column("reaction", sa.String(length=500), nullable=False),
        sa.Column("severity", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_allergies_client_id"), "clinical_allergies", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_allergies_facility_id"),
        "clinical_allergies",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "clinical_encounters",
        sa.Column("encounter_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_type", sa.String(length=40), nullable=False),
        sa.Column("presenting_complaint", sa.Text(), nullable=False),
        sa.Column("medical_history", sa.Text(), nullable=False),
        sa.Column("physical_examination", sa.Text(), nullable=False),
        sa.Column("diagnosis", sa.Text(), nullable=False),
        sa.Column("assessment", sa.Text(), nullable=False),
        sa.Column("plan", sa.Text(), nullable=False),
        sa.Column("follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emergency_action", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_encounters_admission_id"),
        "clinical_encounters",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_encounters_client_id"), "clinical_encounters", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_encounters_clinician_id"),
        "clinical_encounters",
        ["clinician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_encounters_encounter_at"),
        "clinical_encounters",
        ["encounter_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_encounters_facility_id"),
        "clinical_encounters",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "clinical_problems",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=True),
        sa.Column("diagnosis", sa.String(length=500), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("onset_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_problems_admission_id"),
        "clinical_problems",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_problems_client_id"), "clinical_problems", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_problems_facility_id"), "clinical_problems", ["facility_id"], unique=False
    )
    op.create_table(
        "clinical_toxicology_tests",
        sa.Column("test_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("sample_type", sa.String(length=100), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("confirmatory_test", sa.String(length=500), nullable=False),
        sa.Column("confirmatory_result", sa.String(length=500), nullable=False),
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column("acknowledgement", sa.String(length=30), nullable=False),
        sa.Column("acknowledgement_note", sa.String(length=1000), nullable=False),
        sa.Column("follow_up_action", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_toxicology_tests_admission_id"),
        "clinical_toxicology_tests",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_toxicology_tests_client_id"),
        "clinical_toxicology_tests",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_toxicology_tests_facility_id"),
        "clinical_toxicology_tests",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_toxicology_tests_test_at"),
        "clinical_toxicology_tests",
        ["test_at"],
        unique=False,
    )
    op.create_table(
        "clinical_vitals",
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("systolic", sa.Integer(), nullable=True),
        sa.Column("diastolic", sa.Integer(), nullable=True),
        sa.Column("pulse", sa.Integer(), nullable=True),
        sa.Column("respiratory_rate", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("oxygen_saturation", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("blood_glucose", sa.Float(), nullable=True),
        sa.Column("pain_score", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_vitals_admission_id"), "clinical_vitals", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_vitals_client_id"), "clinical_vitals", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_vitals_facility_id"), "clinical_vitals", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_vitals_observed_at"), "clinical_vitals", ["observed_at"], unique=False
    )
    op.create_table(
        "nursing_handovers",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("shift_date", sa.Date(), nullable=False),
        sa.Column("shift", sa.String(length=20), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("outstanding_tasks", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nursing_handovers_admission_id"),
        "nursing_handovers",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nursing_handovers_facility_id"), "nursing_handovers", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_nursing_handovers_shift_date"), "nursing_handovers", ["shift_date"], unique=False
    )
    op.create_table(
        "nursing_notes",
        sa.Column("noted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shift", sa.String(length=20), nullable=False),
        sa.Column("assessment", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("interventions", sa.Text(), nullable=False),
        sa.Column("escalation", sa.Text(), nullable=False),
        sa.Column("escalated_to_id", sa.Uuid(), nullable=True),
        sa.Column("high_risk", sa.Boolean(), nullable=False),
        sa.Column("observation_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["escalated_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nursing_notes_admission_id"), "nursing_notes", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_nursing_notes_client_id"), "nursing_notes", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_nursing_notes_facility_id"), "nursing_notes", ["facility_id"], unique=False
    )
    op.create_index(op.f("ix_nursing_notes_noted_at"), "nursing_notes", ["noted_at"], unique=False)
    op.create_index(
        op.f("ix_nursing_notes_observation_due_at"),
        "nursing_notes",
        ["observation_due_at"],
        unique=False,
    )
    op.create_table(
        "nursing_observations",
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("appetite", sa.String(length=30), nullable=False),
        sa.Column("mood", sa.String(length=100), nullable=False),
        sa.Column("hygiene", sa.String(length=30), nullable=False),
        sa.Column("withdrawal_symptoms", sa.Text(), nullable=False),
        sa.Column("withdrawal_score", sa.Integer(), nullable=True),
        sa.Column("pain_score", sa.Integer(), nullable=True),
        sa.Column("interventions", sa.Text(), nullable=False),
        sa.Column("escalation", sa.Text(), nullable=False),
        sa.Column("next_observation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nursing_observations_admission_id"),
        "nursing_observations",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nursing_observations_client_id"),
        "nursing_observations",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nursing_observations_facility_id"),
        "nursing_observations",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nursing_observations_next_observation_at"),
        "nursing_observations",
        ["next_observation_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nursing_observations_observed_at"),
        "nursing_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_table(
        "clinical_lab_requests",
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("test", sa.String(length=200), nullable=False),
        sa.Column("indication", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("specimen_type", sa.String(length=100), nullable=False),
        sa.Column("specimen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["clinical_encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_lab_requests_admission_id"),
        "clinical_lab_requests",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_lab_requests_client_id"),
        "clinical_lab_requests",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_lab_requests_facility_id"),
        "clinical_lab_requests",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_lab_requests_status"), "clinical_lab_requests", ["status"], unique=False
    )
    op.create_table(
        "clinical_orders",
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("order_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("destination", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completion_note", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["clinical_encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_orders_admission_id"), "clinical_orders", ["admission_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_orders_client_id"), "clinical_orders", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_orders_facility_id"), "clinical_orders", ["facility_id"], unique=False
    )
    op.create_index(op.f("ix_clinical_orders_status"), "clinical_orders", ["status"], unique=False)
    op.create_table(
        "clinical_lab_attachments",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=150), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["clinical_lab_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_lab_attachments_facility_id"),
        "clinical_lab_attachments",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_lab_attachments_request_id"),
        "clinical_lab_attachments",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "clinical_lab_results",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("resulted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("units", sa.String(length=100), nullable=False),
        sa.Column("reference_range", sa.String(length=500), nullable=False),
        sa.Column("abnormal_flag", sa.String(length=30), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["clinical_lab_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_lab_results_facility_id"),
        "clinical_lab_results",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_lab_results_request_id"),
        "clinical_lab_results",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clinical_lab_results_request_id"), table_name="clinical_lab_results")
    op.drop_index(op.f("ix_clinical_lab_results_facility_id"), table_name="clinical_lab_results")
    op.drop_table("clinical_lab_results")
    op.drop_index(
        op.f("ix_clinical_lab_attachments_request_id"), table_name="clinical_lab_attachments"
    )
    op.drop_index(
        op.f("ix_clinical_lab_attachments_facility_id"), table_name="clinical_lab_attachments"
    )
    op.drop_table("clinical_lab_attachments")
    op.drop_index(op.f("ix_clinical_orders_status"), table_name="clinical_orders")
    op.drop_index(op.f("ix_clinical_orders_facility_id"), table_name="clinical_orders")
    op.drop_index(op.f("ix_clinical_orders_client_id"), table_name="clinical_orders")
    op.drop_index(op.f("ix_clinical_orders_admission_id"), table_name="clinical_orders")
    op.drop_table("clinical_orders")
    op.drop_index(op.f("ix_clinical_lab_requests_status"), table_name="clinical_lab_requests")
    op.drop_index(op.f("ix_clinical_lab_requests_facility_id"), table_name="clinical_lab_requests")
    op.drop_index(op.f("ix_clinical_lab_requests_client_id"), table_name="clinical_lab_requests")
    op.drop_index(op.f("ix_clinical_lab_requests_admission_id"), table_name="clinical_lab_requests")
    op.drop_table("clinical_lab_requests")
    op.drop_index(op.f("ix_nursing_observations_observed_at"), table_name="nursing_observations")
    op.drop_index(
        op.f("ix_nursing_observations_next_observation_at"), table_name="nursing_observations"
    )
    op.drop_index(op.f("ix_nursing_observations_facility_id"), table_name="nursing_observations")
    op.drop_index(op.f("ix_nursing_observations_client_id"), table_name="nursing_observations")
    op.drop_index(op.f("ix_nursing_observations_admission_id"), table_name="nursing_observations")
    op.drop_table("nursing_observations")
    op.drop_index(op.f("ix_nursing_notes_observation_due_at"), table_name="nursing_notes")
    op.drop_index(op.f("ix_nursing_notes_noted_at"), table_name="nursing_notes")
    op.drop_index(op.f("ix_nursing_notes_facility_id"), table_name="nursing_notes")
    op.drop_index(op.f("ix_nursing_notes_client_id"), table_name="nursing_notes")
    op.drop_index(op.f("ix_nursing_notes_admission_id"), table_name="nursing_notes")
    op.drop_table("nursing_notes")
    op.drop_index(op.f("ix_nursing_handovers_shift_date"), table_name="nursing_handovers")
    op.drop_index(op.f("ix_nursing_handovers_facility_id"), table_name="nursing_handovers")
    op.drop_index(op.f("ix_nursing_handovers_admission_id"), table_name="nursing_handovers")
    op.drop_table("nursing_handovers")
    op.drop_index(op.f("ix_clinical_vitals_observed_at"), table_name="clinical_vitals")
    op.drop_index(op.f("ix_clinical_vitals_facility_id"), table_name="clinical_vitals")
    op.drop_index(op.f("ix_clinical_vitals_client_id"), table_name="clinical_vitals")
    op.drop_index(op.f("ix_clinical_vitals_admission_id"), table_name="clinical_vitals")
    op.drop_table("clinical_vitals")
    op.drop_index(
        op.f("ix_clinical_toxicology_tests_test_at"), table_name="clinical_toxicology_tests"
    )
    op.drop_index(
        op.f("ix_clinical_toxicology_tests_facility_id"), table_name="clinical_toxicology_tests"
    )
    op.drop_index(
        op.f("ix_clinical_toxicology_tests_client_id"), table_name="clinical_toxicology_tests"
    )
    op.drop_index(
        op.f("ix_clinical_toxicology_tests_admission_id"), table_name="clinical_toxicology_tests"
    )
    op.drop_table("clinical_toxicology_tests")
    op.drop_index(op.f("ix_clinical_problems_facility_id"), table_name="clinical_problems")
    op.drop_index(op.f("ix_clinical_problems_client_id"), table_name="clinical_problems")
    op.drop_index(op.f("ix_clinical_problems_admission_id"), table_name="clinical_problems")
    op.drop_table("clinical_problems")
    op.drop_index(op.f("ix_clinical_encounters_facility_id"), table_name="clinical_encounters")
    op.drop_index(op.f("ix_clinical_encounters_encounter_at"), table_name="clinical_encounters")
    op.drop_index(op.f("ix_clinical_encounters_clinician_id"), table_name="clinical_encounters")
    op.drop_index(op.f("ix_clinical_encounters_client_id"), table_name="clinical_encounters")
    op.drop_index(op.f("ix_clinical_encounters_admission_id"), table_name="clinical_encounters")
    op.drop_table("clinical_encounters")
    op.drop_index(op.f("ix_clinical_allergies_facility_id"), table_name="clinical_allergies")
    op.drop_index(op.f("ix_clinical_allergies_client_id"), table_name="clinical_allergies")
    op.drop_table("clinical_allergies")
    op.drop_index(
        op.f("ix_clinical_note_revisions_facility_id"), table_name="clinical_note_revisions"
    )
    op.drop_index(
        op.f("ix_clinical_note_revisions_entity_id"), table_name="clinical_note_revisions"
    )
    op.drop_table("clinical_note_revisions")
    # ### end Alembic commands ###
