"""Pharmacy stock count register

Revision ID: e20658b750bf
Revises: 942eea8cbd56
"""

import sqlalchemy as sa
from alembic import op

revision = "e20658b750bf"
down_revision = "942eea8cbd56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pharmacy_stock_counts",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("expected_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("counted_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("variance", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("counted_quantity >= 0", name="ck_counted_stock"),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["drug_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pharmacy_stock_counts_batch_id"),
        "pharmacy_stock_counts",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_stock_counts_facility_id"),
        "pharmacy_stock_counts",
        ["facility_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pharmacy_stock_counts_facility_id"), table_name="pharmacy_stock_counts")
    op.drop_index(op.f("ix_pharmacy_stock_counts_batch_id"), table_name="pharmacy_stock_counts")
    op.drop_table("pharmacy_stock_counts")
    # ### end Alembic commands ###
