"""Add Phase 6 to 10 models

Revision ID: ea1c6a40ca6b
Revises: 311f41459de0
"""
from alembic import op
import sqlalchemy as sa


revision = 'ea1c6a40ca6b'
down_revision = '311f41459de0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_registers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payer_type', sa.String(length=50), nullable=False),
    sa.Column('contact_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('stock_level', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aftercare_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIAL', 'PAID', 'CANCELLED', 'WRITTEN_OFF', name='invoicestatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('professional_body', sa.String(length=100), nullable=True),
    sa.Column('licence_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_to_client', sa.String(length=100), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aftercare_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('contact_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('abstinent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['aftercare_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discharge_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=False),
    sa.Column('readiness_checked', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsible_staff_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['responsible_staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('LEAVE', 'HOSPITAL', 'TRANSFER', 'AWOL', 'RETURN', name='movementtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resident_movements')
    op.drop_table('discharge_plans')
    op.drop_table('payments')
    op.drop_table('aftercare_contacts')
    op.drop_table('visitors')
    op.drop_table('staff_profiles')
    op.drop_table('invoices')
    op.drop_table('incidents')
    op.drop_table('aftercare_cases')
    op.drop_table('store_items')
    op.drop_table('payers')
    op.drop_table('compliance_registers')
    # ### end Alembic commands ###
